import { http, HttpResponse } from 'msw';
import { API_BASE_URL } from '@shared/api/client';
import { errorResponse } from './_helpers';

/**
 * MSW handlers for the AUDIT TRAIL (D45 §46, §53).
 *
 * ⚠️ Module agents: do NOT edit this file — the audit trail is owned here.
 *
 * The demo serves a small hand-written set of entries **already in the shape the server
 * renders**, because that shape is the whole feature. The real endpoint turns
 * `grade.update / entity_id f84c4f15-… / {"entries": 3}` into a sentence naming a person
 * and a before/after; a mock that returned raw rows would demo the opposite of what was
 * built, and would let the screen quietly grow a dependency on a technical field the real
 * API does not send.
 *
 * Read-only, mirroring the server: there is no write endpoint for `audit_log` and no mock
 * of one.
 *
 * **THE ONE AUDIT MOCK (Sep 2026).** `GET /settings/audit-log` and its `demoAuditRows()`
 * synthesiser are deleted from `handlers/settings.ts`; a second mock door would have kept
 * the removed screen demoable, which is how a deleted feature comes back.
 */
const NOW = '09/09/2026';

interface MockEntry {
  id: number;
  date: string;
  time: string;
  who: string;
  who_role: string | null;
  module: string;
  what: string;
  description: string;
  subject: string | null;
  context: string | null;
  changes: { field: string; previous: string | null; new: string | null }[];
  reason: string | null;
  ip_address: string | null;
  /** What KIND of record. Carried over when the two audit screens merged (Sep 2026). */
  record: string | null;
  /** "Entry #5001" — the handle an auditor quotes. */
  reference: string;
  /** Recorded facts that are not before/after values. */
  details: { label: string; value: string }[];
}

const ENTRIES: MockEntry[] = [
  {
    id: 5001,
    date: NOW,
    time: '2:14 PM',
    who: 'Alicia Cano',
    who_role: 'Lecturer',
    module: 'Grades',
    what: 'Grade changed',
    description:
      'Alicia Cano changed the grade for Fernando Perez (S-25035) on Quiz 1: score 17 to 19, letter grade B+ to A.',
    subject: 'Fernando Perez (S-25035)',
    context: 'Pre-Calculus (MATH1210-01)',
    changes: [
      { field: 'Score', previous: '17', new: '19' },
      { field: 'Letter grade', previous: 'B+', new: 'A' },
    ],
    reason: null,
    ip_address: '192.168.10.24',
    record: 'Grade',
    reference: 'Entry #5001',
    details: [],
  },
  {
    id: 5000,
    date: NOW,
    time: '11:02 AM',
    who: 'Alicia Mendez',
    who_role: 'Dean',
    module: 'Registration',
    what: 'Registration restriction overridden',
    description:
      'Alicia Mendez overrode the prerequisite requirement to register Trevaughn Vasquez (S-25016) in Pre-Calculus (MATH1210-01) — MATH1110 (Taken but not passed (earned F)).',
    subject: 'Trevaughn Vasquez (S-25016)',
    context: 'Pre-Calculus (MATH1210-01)',
    changes: [],
    reason: 'Sat and passed the August make-up examination; transcript to follow.',
    ip_address: '192.168.10.8',
    record: 'Registration',
    reference: 'Entry #5000',
    // WHICH rule and WHICH requirement. Both were in the stored summary all along and
    // neither reached a screen: the raw one buried them in JSON, the narrative one
    // dropped them. This row is also the one that exposed the disclosure defect — a
    // reason is rendered ABOVE the collapse, so "Show detail" opened onto nothing.
    details: [
      { label: 'Rule waived', value: 'Course prerequisite' },
      { label: 'Requirement', value: 'MATH1110 (Taken but not passed (earned F))' },
    ],
  },
  {
    id: 4999,
    date: '08/09/2026',
    time: '4:47 PM',
    who: 'Rosa Chan',
    who_role: 'Registrar',
    module: 'Students',
    what: 'Student status changed',
    description: 'Rosa Chan changed the status of Leah Williams (S-25030) from Active to Inactive.',
    subject: 'Leah Williams (S-25030)',
    context: null,
    changes: [{ field: 'Status', previous: 'Active', new: 'Inactive' }],
    reason: null,
    ip_address: '192.168.10.31',
    record: 'Student record',
    reference: 'Entry #4999',
    // Deliberately empty: the status is in `changes`, and one fact under two headings
    // reads as two facts. The server suppresses it the same way.
    details: [],
  },
  {
    id: 4998,
    date: '08/09/2026',
    time: '9:15 AM',
    who: 'Alicia Mendez',
    who_role: 'Dean',
    module: 'Courses',
    what: 'Prerequisite removed',
    description:
      'Alicia Mendez removed a prerequisite from Pre-Calculus (MATH1210), and cleared the printed requirement text “MATH1110”.',
    subject: 'Pre-Calculus (MATH1210)',
    context: null,
    changes: [],
    reason: null,
    ip_address: '192.168.10.8',
    record: 'Course prerequisite',
    reference: 'Entry #4998',
    details: [
      { label: 'Printed requirement text cleared', value: 'MATH1110' },
    ],
  },
];

const REPORTS = [
  { key: 'grade_changes', name: 'Grade changes', action_count: 6 },
  { key: 'student_records', name: 'Student record changes', action_count: 6 },
  { key: 'registration_overrides', name: 'Registration overrides', action_count: 6 },
  { key: 'system_activity', name: 'System activity', action_count: 12 },
];

const REPORT_MODULES: Record<string, string[]> = {
  grade_changes: ['Grades'],
  student_records: ['Students'],
  registration_overrides: ['Registration', 'Courses'],
  system_activity: ['Users and access', 'System settings', 'Academic calendar'],
};

/**
 * Dean and Auditor only — mirrors `require_role(PRINCIPAL, AUDITOR)` on the server.
 *
 * ⚠️ `sysadmin` WAS IN THIS LIST and is not any more (Sep 2026). The server never
 * allowed them on `/audit`: D45 Phase 7's central `technical_role_scope` guard refused
 * the role and the route was corrected, because this trail is mostly academic records
 * and §48 keeps that role out of exactly those. The demo was allowing them, which is
 * how a demo certifies behaviour the backend does not have — for the fourth recorded
 * time in this project. The Registrar is absent for the reason the server gives: they
 * are the log's most frequent subject.
 */
function assertReader(cookies: Record<string, string>) {
  const role = cookies['sis_mock_session'] ?? 'principal';
  if (!['principal', 'auditor'].includes(role)) {
    return errorResponse(403, 'forbidden', 'You do not have access to this resource.');
  }
  return null;
}

export const auditHandlers = [
  http.get(`${API_BASE_URL}/audit`, ({ request, cookies }) => {
    const denied = assertReader(cookies);
    if (denied) return denied;

    const url = new URL(request.url);
    const report = url.searchParams.get('report');
    const module = url.searchParams.get('module');
    const search = (url.searchParams.get('search') ?? '').toLowerCase();

    let items = ENTRIES;
    if (report) {
      const allowed = REPORT_MODULES[report] ?? [];
      items = items.filter((e) => allowed.includes(e.module));
    }
    if (module) items = items.filter((e) => e.module === module);
    if (search) {
      items = items.filter((e) =>
        `${e.description} ${e.subject ?? ''} ${e.reason ?? ''}`.toLowerCase().includes(search),
      );
    }

    return HttpResponse.json({
      items,
      total: items.length,
      page: 1,
      page_size: 25,
      // The demo set is entirely post-Phase-7, so the "before/after unavailable" notice
      // stays off. Flipping this to true is the way to see that state.
      includes_pre_phase7_rows: false,
    });
  }),

  http.get(`${API_BASE_URL}/audit/filters`, ({ cookies }) => {
    const denied = assertReader(cookies);
    if (denied) return denied;
    return HttpResponse.json({
      modules: [...new Set(ENTRIES.map((e) => e.module))],
      actions: REPORTS.map((r) => r.key),
      actors: [
        { id: 'mock-dean', name: 'Alicia Mendez', role: 'Dean' },
        { id: 'mock-lecturer', name: 'Alicia Cano', role: 'Lecturer' },
        { id: 'mock-registrar', name: 'Rosa Chan', role: 'Registrar' },
      ],
    });
  }),

  http.get(`${API_BASE_URL}/audit/reports`, ({ cookies }) => {
    const denied = assertReader(cookies);
    if (denied) return denied;
    return HttpResponse.json(REPORTS);
  }),
];
