import { http, HttpResponse } from 'msw';
import { API_BASE_URL } from '@shared/api/client';
import { DEMO_DATASET } from '@shared/api/mocks/demo/dataset';
import type { DemoClassroom } from '@shared/api/mocks/demo/types';
import { errorResponse, listParamsFrom } from './_helpers';

/**
 * MSW handlers for CLASSROOMS (D44), backing Settings → Classrooms and the room picker on
 * the offering form.
 *
 * ⚠️ Module agents: do NOT edit this file — classrooms are owned here.
 *
 * Three server rules are mirrored deliberately, because demo mode has certified a screen as
 * working before that the real backend then refused:
 *
 *  1. **Dean + Registrar write.** Rooms are estate administration, the same pair that owns
 *     offerings and scheduling.
 *  2. **Occupancy cannot be SET.** `In-Use`/`Available`/`Occupied` are storable (the
 *     client's own data uses them) but not writable — they describe live occupancy, which
 *     the timetable derives.
 *  3. **Deleting a room in use is refused.** The FK is `ON DELETE SET NULL`, so the
 *     database would silently unroom every class in it.
 */
const D = DEMO_DATASET;

const SETTABLE = ['Active', 'Inactive'];

function assertManage(cookies: Record<string, string>) {
  const role = cookies['sis_mock_session'] ?? 'principal';
  if (role !== 'principal' && role !== 'secretary') {
    return errorResponse(403, 'forbidden', 'Only the Dean or Registrar can change classrooms.');
  }
  return null;
}

const label = (room: DemoClassroom) => `${room.room_code} · ${room.building}`;

/** Live offerings scheduled here — what the delete guard and the list column read. */
const offeringCount = (roomId: string) =>
  D.offerings.filter((o) => o.classroom_id === roomId).length;

function view(room: DemoClassroom) {
  return {
    id: room.id,
    room_code: room.room_code,
    building: room.building,
    capacity: room.capacity,
    room_type: room.room_type,
    status: room.status,
    label: label(room),
    offering_count: offeringCount(room.id),
    created_on: room.created_on,
    edited_on: room.edited_on,
  };
}

let seq = 0;
const nextId = () => {
  seq += 1;
  return `room-demo-${seq}`;
};

export const classroomsHandlers = [
  // GET /classrooms — ordered building then code, the way a person looks for a room.
  http.get(`${API_BASE_URL}/classrooms`, ({ request }) => {
    const url = new URL(request.url);
    // `listParamsFrom` leaves both absent when the query string omits them; the API
    // defaults are 1 and 25.
    const { page = 1, page_size: pageSize = 25, search } = listParamsFrom(url);
    const status = url.searchParams.get('status');

    let rows = [...D.classrooms];
    if (status) rows = rows.filter((r) => r.status === status);
    if (search) {
      const q = search.toLowerCase();
      rows = rows.filter(
        (r) =>
          r.room_code.toLowerCase().includes(q) ||
          r.building.toLowerCase().includes(q) ||
          (r.room_type ?? '').toLowerCase().includes(q),
      );
    }
    rows.sort(
      (a, b) => a.building.localeCompare(b.building) || a.room_code.localeCompare(b.room_code),
    );

    const total = rows.length;
    const start = (page - 1) * pageSize;
    return HttpResponse.json({
      items: rows.slice(start, start + pageSize).map(view),
      total,
      page,
      page_size: pageSize,
      total_pages: Math.max(1, Math.ceil(total / pageSize)),
    });
  }),

  http.get(`${API_BASE_URL}/classrooms/:roomId`, ({ params }) => {
    const room = D.classrooms.find((r) => r.id === String(params.roomId));
    if (!room) return errorResponse(404, 'not_found', 'Classroom not found.');
    return HttpResponse.json(view(room));
  }),

  http.post(`${API_BASE_URL}/classrooms`, async ({ request, cookies }) => {
    const denied = assertManage(cookies);
    if (denied) return denied;
    const body = (await request.json()) as Partial<DemoClassroom>;

    if (!body.room_code?.trim() || !body.building?.trim()) {
      return errorResponse(422, 'validation_error', 'A classroom needs a room code and a building.');
    }
    if (body.status && !SETTABLE.includes(body.status)) {
      return errorResponse(
        422,
        'classroom_status_not_settable',
        'A room is set Active or Inactive. In-Use, Available and Occupied describe live occupancy.',
      );
    }
    // Case-insensitive, matching the collation the real check runs under.
    const clash = D.classrooms.some(
      (r) => r.room_code.toLowerCase() === body.room_code!.trim().toLowerCase(),
    );
    if (clash) {
      return errorResponse(
        409,
        'duplicate_room_code',
        `A classroom with code ${body.room_code.trim()} already exists.`,
      );
    }

    const room: DemoClassroom = {
      id: nextId(),
      room_code: body.room_code.trim(),
      building: body.building.trim(),
      capacity: body.capacity ?? 0,
      room_type: body.room_type?.trim() || null,
      status: body.status ?? 'Active',
      created_on: new Date().toISOString(),
      // NULL until edited — the 015 convention.
      edited_on: null,
    };
    D.classrooms.push(room);
    return HttpResponse.json(view(room), { status: 201 });
  }),

  http.patch(`${API_BASE_URL}/classrooms/:roomId`, async ({ params, request, cookies }) => {
    const denied = assertManage(cookies);
    if (denied) return denied;
    const room = D.classrooms.find((r) => r.id === String(params.roomId));
    if (!room) return errorResponse(404, 'not_found', 'Classroom not found.');
    const body = (await request.json()) as Partial<DemoClassroom>;

    if (body.status !== undefined && !SETTABLE.includes(body.status)) {
      return errorResponse(
        422,
        'classroom_status_not_settable',
        'A room is set Active or Inactive. In-Use, Available and Occupied describe live occupancy.',
      );
    }
    if (body.room_code !== undefined) {
      const wanted = body.room_code.trim();
      if (!wanted) return errorResponse(422, 'validation_error', 'A classroom needs a room code.');
      const clash = D.classrooms.some(
        (r) => r.id !== room.id && r.room_code.toLowerCase() === wanted.toLowerCase(),
      );
      if (clash) {
        return errorResponse(
          409,
          'duplicate_room_code',
          `A classroom with code ${wanted} already exists.`,
        );
      }
      room.room_code = wanted;
    }
    // Only the keys PRESENT, so a partial save cannot blank what it omits.
    if (body.building !== undefined) room.building = body.building.trim();
    if (body.capacity !== undefined) room.capacity = body.capacity ?? 0;
    if (body.room_type !== undefined) room.room_type = body.room_type?.trim() || null;
    if (body.status !== undefined) room.status = body.status;
    room.edited_on = new Date().toISOString();

    return HttpResponse.json(view(room));
  }),

  http.delete(`${API_BASE_URL}/classrooms/:roomId`, ({ params, cookies }) => {
    const denied = assertManage(cookies);
    if (denied) return denied;
    const index = D.classrooms.findIndex((r) => r.id === String(params.roomId));
    const room = D.classrooms[index];
    if (index === -1 || !room) return errorResponse(404, 'not_found', 'Classroom not found.');

    const inUse = offeringCount(room.id);
    if (inUse) {
      return errorResponse(
        409,
        'classroom_in_use',
        `${label(room)} is assigned to ${inUse} course offering${inUse === 1 ? '' : 's'}. ` +
          'Reassign them before deleting the room, or set it Inactive instead.',
      );
    }
    D.classrooms.splice(index, 1);
    return new HttpResponse(null, { status: 204 });
  }),
];
