import { http, HttpResponse } from 'msw';
import { API_BASE_URL } from '@shared/api/client';
import { DEMO_DATASET, listCourses } from '@shared/api/mocks/demo/dataset';
import type { DemoCourse } from '@shared/api/mocks/demo/dataset';
import { boolParam, errorResponse, listParamsFrom } from './_helpers';

/**
 * MSW handlers for the COURSE CATALOG (api-spec §5b), backing Settings › Courses
 * (features/settings/CoursesPage.tsx). Response shapes match the orval-generated models
 * (PageCourseListItem / CourseDetail).
 *
 * Endpoints: GET /courses (paginated picker/catalog), POST/PATCH/DELETE with the documented
 * 409 guards (duplicate name/code, course in use).
 *
 * **D31** — the path is `/courses`, not `/subjects`, and the three error codes moved with
 * it: `duplicate_course_name`, `duplicate_course_code`, `course_in_use`. Those codes are
 * what `shared/api/errorMessages.ts` keys its copy on, and a stale key there is invisible —
 * the lookup misses and the server's own sentence is shown instead — so both sides had to
 * change together.
 *
 * ⚠️ Module agents: do NOT edit this file — the course catalog is owned here. The array is
 * wired into handlers/index.ts already.
 */
const D = DEMO_DATASET;

function toListItem(c: DemoCourse) {
  return {
    id: c.id,
    name: c.name,
    code: c.code,
    // D30 §D2 — `credits` is what closes the grade→credit chain (plan §B3), so it is
    // part of the list shape on the real API and has to be here too.
    credits: c.credits,
    component: c.component,
    is_active: c.is_active,
  };
}

/**
 * D30 — the course catalog is Dean-only to WRITE (brief §6); reads stay open.
 *
 * This gate exists because of a real defect the team already paid for once: in D29,
 * `GET /settings/academic-years` was principal-only on the server while the MSW handler
 * had no role gate at all, so demo mode certified a screen as working that returned 403
 * for every teacher against the real backend. Mirroring the server here is what stops
 * that class of mismatch from hiding again.
 */
function assertDean(cookies: Record<string, string>) {
  const role = cookies['sis_mock_session'] ?? 'principal';
  if (role !== 'principal') {
    return errorResponse(403, 'forbidden', 'Only the Dean can change the course catalog.');
  }
  return null;
}

export const coursesHandlers = [
  http.get(`${API_BASE_URL}/courses`, ({ request }) => {
    const url = new URL(request.url);
    const page = listCourses({
      ...listParamsFrom(url),
      is_active: boolParam(url, 'is_active'),
      include_retired: boolParam(url, 'include_retired') === true,
    });
    return HttpResponse.json({ ...page, items: page.items.map(toListItem) });
  }),

  http.post(`${API_BASE_URL}/courses`, async ({ request, cookies }) => {
    const denied = assertDean(cookies);
    if (denied) return denied;
    const body = (await request.json()) as {
      name: string;
      code?: string;
      credits?: number;
      component?: DemoCourse['component'];
    };
    // D30: `code` is REQUIRED — `courses.code` is NOT NULL. Mirrored here so demo mode
    // cannot certify a code-less create the real backend answers with a 422.
    if (!body.name || !body.code) {
      return errorResponse(422, 'validation_error', 'Some fields need attention.', {
        ...(body.name ? {} : { name: ['Field required'] }),
        ...(body.code ? {} : { code: ['Field required'] }),
      });
    }
    if (body.credits !== undefined && (!Number.isInteger(body.credits) || body.credits < 1)) {
      return errorResponse(422, 'validation_error', 'Some fields need attention.', {
        credits: ['Must be a whole number greater than 0.'],
      });
    }
    if (D.courses.some((c) => c.name.toLowerCase() === body.name.toLowerCase())) {
      return errorResponse(409, 'duplicate_course_name', 'A course with this name already exists.');
    }
    if (D.courses.some((c) => c.code.toLowerCase() === body.code!.toLowerCase())) {
      return errorResponse(409, 'duplicate_course_code', 'A course with this code already exists.');
    }
    const created: DemoCourse = {
      id: `course-new-${D.courses.length + 1}`,
      name: body.name,
      code: body.code,
      credits: body.credits ?? 3,
      component: body.component ?? null,
      is_active: true,
    };
    D.courses.push(created);
    return HttpResponse.json(toListItem(created), { status: 201 });
  }),

  http.patch(`${API_BASE_URL}/courses/:courseId`, async ({ params, request, cookies }) => {
    const denied = assertDean(cookies);
    if (denied) return denied;
    const course = D.courses.find((c) => c.id === params.courseId);
    if (!course) return errorResponse(404, 'not_found', 'Course not found.');
    const body = (await request.json()) as {
      name?: string;
      code?: string;
      credits?: number;
      component?: DemoCourse['component'];
      is_active?: boolean;
    };
    if (
      body.name &&
      D.courses.some((c) => c.id !== course.id && c.name.toLowerCase() === body.name!.toLowerCase())
    ) {
      return errorResponse(409, 'duplicate_course_name', 'A course with this name already exists.');
    }
    if (
      body.code &&
      D.courses.some((c) => c.id !== course.id && c.code.toLowerCase() === body.code!.toLowerCase())
    ) {
      return errorResponse(409, 'duplicate_course_code', 'A course with this code already exists.');
    }
    if (body.name !== undefined) course.name = body.name;
    // The code cannot be cleared — the column is NOT NULL (D30).
    if (body.code) course.code = body.code;
    if (body.credits !== undefined) course.credits = body.credits;
    if (body.component !== undefined) course.component = body.component;
    if (body.is_active !== undefined) course.is_active = body.is_active;
    return HttpResponse.json(toListItem(course));
  }),

  http.delete(`${API_BASE_URL}/courses/:courseId`, ({ params, cookies }) => {
    const denied = assertDean(cookies);
    if (denied) return denied;
    const course = D.courses.find((c) => c.id === params.courseId);
    if (!course) return errorResponse(404, 'not_found', 'Course not found.');
    // In use = scheduled by any offering. D31: one check against one table, where it used
    // to have to ask the `class_subjects` join whether anything pointed at the subject.
    const inUse = D.offerings.some((o) => o.course_id === course.id);
    if (inUse) {
      return errorResponse(
        409,
        'course_in_use',
        'Offered in one or more course offerings — retire it instead.',
      );
    }
    D.courses = D.courses.filter((c) => c.id !== course.id);
    return new HttpResponse(null, { status: 204 });
  }),
];
