import { http, HttpResponse } from 'msw';
import { API_BASE_URL } from '@shared/api/client';
import { DEMO_DATASET } from '@shared/api/mocks/demo/dataset';
import type { DemoCoursePrerequisite } from '@shared/api/mocks/demo/types';
import { errorResponse } from './_helpers';

/**
 * MSW handlers for COURSE PREREQUISITES (D30 §D4), backing the Prerequisites dialog
 * on Settings → Courses.
 *
 * ⚠️ Module agents: do NOT edit this file — prerequisites are owned here.
 *
 * Mounted under `/courses/{id}/prerequisites`, matching the server. It was
 * `/subjects/{id}/...` until D31, kept there on the reasoning that "the catalog entity
 * already has a route, and giving one entity two spellings would be worse than the single
 * legacy name" — which was right, and is exactly why it moved when the catalog route did.
 *
 * Reads are ungated (prospectus material); writes are Dean-only, mirroring §D14 — a
 * demo that let the Registrar edit prerequisites would certify a screen the real
 * backend answers 403 for.
 */
const D = DEMO_DATASET;

function assertDean(cookies: Record<string, string>) {
  const role = cookies['sis_mock_session'] ?? 'principal';
  if (role !== 'principal') {
    return errorResponse(403, 'forbidden', 'Only the Dean can change prerequisites.');
  }
  return null;
}

function list(courseId: string) {
  const course = D.courses.find((c) => c.id === courseId);
  return {
    items: D.course_prerequisites
      .filter((p) => p.course_id === courseId)
      .map((p) => {
        const required = p.prerequisite_course_id
          ? D.courses.find((c) => c.id === p.prerequisite_course_id)
          : undefined;
        const program = p.program_id
          ? D.programs.find((x) => x.id === p.program_id)
          : undefined;
        return {
          id: p.id,
          requirement_type: p.requirement_type,
          prerequisite_course: required
            ? { id: required.id, code: required.code, name: required.name }
            : null,
          program: program
            ? { id: program.id, code: program.code, name: program.name }
            : null,
        };
      }),
    // Documentation only — the gate reads `items`. The demo courses carry none.
    prerequisites_text: (course as { prerequisites_text?: string } | undefined)
      ?.prerequisites_text ?? null,
  };
}

export const prerequisitesHandlers = [
  http.get(`${API_BASE_URL}/courses/:courseId/prerequisites`, ({ params }) => {
    const courseId = String(params.courseId);
    if (!D.courses.some((c) => c.id === courseId)) {
      return errorResponse(404, 'not_found', 'Course not found.');
    }
    return HttpResponse.json(list(courseId));
  }),

  http.post(
    `${API_BASE_URL}/courses/:courseId/prerequisites`,
    async ({ params, request, cookies }) => {
      const denied = assertDean(cookies);
      if (denied) return denied;
      const courseId = String(params.courseId);
      if (!D.courses.some((c) => c.id === courseId)) {
        return errorResponse(404, 'not_found', 'Course not found.');
      }
      const body = (await request.json()) as {
        requirement_type?: DemoCoursePrerequisite['requirement_type'];
        prerequisite_course_id?: string | null;
        program_id?: string | null;
      };
      const kind = body.requirement_type ?? 'course';

      if (kind === 'all_program_courses') {
        if (!body.program_id) {
          return errorResponse(422, 'validation_error', 'Some fields need attention.', {
            program_id: ['Required for all_program_courses.'],
          });
        }
        if (body.prerequisite_course_id) {
          return errorResponse(422, 'validation_error', 'Some fields need attention.', {
            prerequisite_course_id: ['Must be omitted.'],
          });
        }
      } else {
        if (!body.prerequisite_course_id) {
          return errorResponse(422, 'validation_error', 'Some fields need attention.', {
            prerequisite_course_id: ['Required.'],
          });
        }
        if (body.prerequisite_course_id === courseId) {
          return errorResponse(422, 'validation_error', 'Some fields need attention.', {
            prerequisite_course_id: ['Cannot be this course.'],
          });
        }
      }

      if (
        D.course_prerequisites.some(
          (p) =>
            p.course_id === courseId &&
            p.prerequisite_course_id === (body.prerequisite_course_id ?? null) &&
            p.program_id === (body.program_id ?? null),
        )
      ) {
        return errorResponse(
          409,
          'duplicate_prerequisite',
          'That prerequisite is already recorded for this course.',
        );
      }

      D.course_prerequisites.push({
        id: `prereq-new-${D.course_prerequisites.length + 1}`,
        course_id: courseId,
        prerequisite_course_id: body.prerequisite_course_id ?? null,
        program_id: body.program_id ?? null,
        requirement_type: kind,
      });
      return HttpResponse.json(list(courseId), { status: 201 });
    },
  ),

  http.delete(
    `${API_BASE_URL}/courses/:courseId/prerequisites/:prerequisiteId`,
    ({ params, cookies }) => {
      const denied = assertDean(cookies);
      if (denied) return denied;
      const courseId = String(params.courseId);
      // Scoped to the course in the path — by id alone, one course's URL could delete
      // another's requirement.
      const row = D.course_prerequisites.find(
        (p) => p.id === params.prerequisiteId && p.course_id === courseId,
      );
      if (!row) return errorResponse(404, 'not_found', 'Prerequisite not found.');
      D.course_prerequisites = D.course_prerequisites.filter((p) => p.id !== row.id);
      return HttpResponse.json(list(courseId));
    },
  ),
];
