import { http, HttpResponse } from 'msw';
import { API_BASE_URL } from '@shared/api/client';
import { DEMO_DATASET } from '@shared/api/mocks/demo/dataset';
import type { DemoProgram, DemoProgramCourse } from '@shared/api/mocks/demo/types';
import { boolParam, errorResponse, listParamsFrom } from './_helpers';

/**
 * MSW handlers for PROGRAMMES / STUDIES and their curriculum (D30 §D3), backing
 * Settings → Programmes and the curriculum builder.
 *
 * ⚠️ Module agents: do NOT edit this file — programmes are owned here.
 *
 * Two things this mirrors from the real server on purpose:
 *
 *  1. **Dean-only writes** (§D14, brief §6). Demo mode has certified a screen as
 *     working before that the real backend answered 403 for — `GET
 *     /settings/academic-years` was principal-only on the server while the MSW handler
 *     had no gate at all. Mirroring the gate is what stops that class of mismatch.
 *
 *  2. **Every curriculum write returns the WHOLE programme**, because each one changes
 *     the block's credit total and the programme's total, and the builder would
 *     otherwise have to re-fetch after each edit.
 */
const D = DEMO_DATASET;

function assertDean(cookies: Record<string, string>) {
  const role = cookies['sis_mock_session'] ?? 'principal';
  if (role !== 'principal') {
    return errorResponse(403, 'forbidden', 'Only the Dean can change programmes.');
  }
  return null;
}

function curriculumRows(programId: string): DemoProgramCourse[] {
  return D.program_courses.filter((pc) => pc.program_id === programId);
}

function totals(programId: string) {
  const rows = curriculumRows(programId);
  const credits = rows.reduce((sum, pc) => {
    const course = D.courses.find((c) => c.id === pc.course_id);
    return sum + (course?.credits ?? 0);
  }, 0);
  return { course_count: rows.length, curriculum_credits: credits };
}

function listItem(p: DemoProgram) {
  return {
    id: p.id,
    code: p.code,
    name: p.name,
    award: p.award,
    total_credits: p.total_credits,
    min_passing_grade_point: p.min_passing_grade_point,
    is_active: p.is_active,
    ...totals(p.id),
  };
}

/**
 * The plan, grouped into blocks ordered by `term_order` — NOT by `term_label`.
 *
 * Primary Education runs Summer 1 · Sem 1 · Sem 2 · **Spring 1** · Sem 3, and "Spring
 * 1" sorts before "Summer 1" alphabetically, so ordering by the label would put the
 * plan in the wrong sequence. Courses within a block go by code, as the source
 * sequences print them.
 */
function detail(p: DemoProgram) {
  const blocks = new Map<
    number,
    { term_label: string; term_order: number; credits: number; courses: unknown[] }
  >();

  const rows = [...curriculumRows(p.id)].sort((a, b) => {
    if (a.term_order !== b.term_order) return a.term_order - b.term_order;
    const ca = D.courses.find((c) => c.id === a.course_id)?.code ?? '';
    const cb = D.courses.find((c) => c.id === b.course_id)?.code ?? '';
    return ca.localeCompare(cb);
  });

  for (const pc of rows) {
    const course = D.courses.find((c) => c.id === pc.course_id);
    if (!course) continue;
    let block = blocks.get(pc.term_order);
    if (!block) {
      block = {
        term_label: pc.term_label,
        term_order: pc.term_order,
        credits: 0,
        courses: [],
      };
      blocks.set(pc.term_order, block);
    }
    block.courses.push({
      id: pc.id,
      course: {
        id: course.id,
        code: course.code,
        name: course.name,
        credits: course.credits,
        component: course.component,
        is_active: course.is_active,
      },
      is_required: pc.is_required,
    });
    block.credits += course.credits;
  }

  return { ...listItem(p), curriculum: [...blocks.values()] };
}

function findProgram(id: string): DemoProgram | undefined {
  return D.programs.find((p) => p.id === id);
}

export const programsHandlers = [
  http.get(`${API_BASE_URL}/programs`, ({ request }) => {
    const url = new URL(request.url);
    const { page = 1, page_size = 25, search } = listParamsFrom(url);
    const isActive = boolParam(url, 'is_active');
    const includeRetired = boolParam(url, 'include_retired') === true;

    let rows = D.programs;
    // Default to active-only, like the course catalog: the common caller is a picker.
    // ⚠️ `boolParam` reports an ABSENT param as `null`, not `undefined`. Comparing against
    // `undefined` here made the unfiltered call — the one the admissions wizard's
    // programme picker sends — fall through to `p.is_active === null`, which is false for
    // every row, so the picker received an EMPTY list while the endpoint answered 200.
    // `include_retired` drops the filter outright — the only way to get BOTH, since
    // `is_active` is an equality filter and its absence re-applies the active-only
    // default. Mirrors the server, so demo mode cannot certify a switch the real
    // backend leaves inert.
    if (!includeRetired) {
      rows = rows.filter((p) => (isActive === null ? p.is_active : p.is_active === isActive));
    }
    if (search) {
      const q = search.toLowerCase();
      rows = rows.filter(
        (p) =>
          p.code.toLowerCase().includes(q) ||
          p.name.toLowerCase().includes(q) ||
          (p.award ?? '').toLowerCase().includes(q),
      );
    }
    rows = [...rows].sort((a, b) => a.code.localeCompare(b.code));

    const start = (page - 1) * page_size;
    return HttpResponse.json({
      items: rows.slice(start, start + page_size).map(listItem),
      total: rows.length,
      page,
      page_size,
      total_pages: Math.max(1, Math.ceil(rows.length / page_size)),
    });
  }),

  http.get(`${API_BASE_URL}/programs/:programId`, ({ params }) => {
    const program = findProgram(String(params.programId));
    if (!program) return errorResponse(404, 'not_found', 'Program not found.');
    return HttpResponse.json(detail(program));
  }),

  http.post(`${API_BASE_URL}/programs`, async ({ request, cookies }) => {
    const denied = assertDean(cookies);
    if (denied) return denied;
    const body = (await request.json()) as Partial<DemoProgram>;
    if (!body.code || !body.name) {
      return errorResponse(422, 'validation_error', 'Some fields need attention.', {
        ...(body.code ? {} : { code: ['Field required'] }),
        ...(body.name ? {} : { name: ['Field required'] }),
      });
    }
    if (D.programs.some((p) => p.code.toLowerCase() === body.code!.toLowerCase())) {
      return errorResponse(409, 'duplicate_program_code', 'A program with this code already exists.');
    }
    if (D.programs.some((p) => p.name.toLowerCase() === body.name!.toLowerCase())) {
      return errorResponse(409, 'duplicate_program_name', 'A program with this name already exists.');
    }
    const created: DemoProgram = {
      id: `prog-new-${D.programs.length + 1}`,
      code: body.code,
      name: body.name,
      award: body.award ?? null,
      total_credits: body.total_credits ?? null,
      min_passing_grade_point: body.min_passing_grade_point ?? '2.50',
      is_active: true,
    };
    D.programs.push(created);
    return HttpResponse.json(detail(created), { status: 201 });
  }),

  http.patch(`${API_BASE_URL}/programs/:programId`, async ({ params, request, cookies }) => {
    const denied = assertDean(cookies);
    if (denied) return denied;
    const program = findProgram(String(params.programId));
    if (!program) return errorResponse(404, 'not_found', 'Program not found.');
    const body = (await request.json()) as Partial<DemoProgram>;
    if (
      body.code &&
      D.programs.some((p) => p.id !== program.id && p.code.toLowerCase() === body.code!.toLowerCase())
    ) {
      return errorResponse(409, 'duplicate_program_code', 'A program with this code already exists.');
    }
    if (body.code !== undefined) program.code = body.code;
    if (body.name !== undefined) program.name = body.name;
    if (body.award !== undefined) program.award = body.award ?? null;
    if (body.total_credits !== undefined) program.total_credits = body.total_credits ?? null;
    if (body.min_passing_grade_point !== undefined) {
      program.min_passing_grade_point = body.min_passing_grade_point;
    }
    if (body.is_active !== undefined) program.is_active = body.is_active;
    return HttpResponse.json(detail(program));
  }),

  http.delete(`${API_BASE_URL}/programs/:programId`, ({ params, cookies }) => {
    const denied = assertDean(cookies);
    if (denied) return denied;
    const program = findProgram(String(params.programId));
    if (!program) return errorResponse(404, 'not_found', 'Program not found.');
    // The real guard is "no student is registered on it". Demo students carry no
    // programme yet (that is Phase 4, §D12), so nothing here can trip it — the code
    // exists so the branch is not invented later under time pressure.
    D.program_courses = D.program_courses.filter((pc) => pc.program_id !== program.id);
    D.programs = D.programs.filter((p) => p.id !== program.id);
    return new HttpResponse(null, { status: 204 });
  }),

  // ── Curriculum ────────────────────────────────────────────────────────────────
  http.post(`${API_BASE_URL}/programs/:programId/courses`, async ({ params, request, cookies }) => {
    const denied = assertDean(cookies);
    if (denied) return denied;
    const program = findProgram(String(params.programId));
    if (!program) return errorResponse(404, 'not_found', 'Program not found.');
    const body = (await request.json()) as {
      course_id: string;
      term_label: string;
      term_order: number;
      is_required?: boolean;
    };
    const course = D.courses.find((c) => c.id === body.course_id);
    if (!course) return errorResponse(404, 'course_not_found', 'Course not found.');
    if (!course.is_active) {
      return errorResponse(409, 'course_retired', 'That course is retired.');
    }
    if (
      D.program_courses.some(
        (pc) => pc.program_id === program.id && pc.course_id === course.id,
      )
    ) {
      return errorResponse(
        409,
        'course_already_in_program',
        'That course is already in this program.',
      );
    }
    D.program_courses.push({
      id: `pc-new-${D.program_courses.length + 1}`,
      program_id: program.id,
      course_id: course.id,
      term_label: body.term_label,
      term_order: body.term_order,
      is_required: body.is_required ?? true,
    });
    return HttpResponse.json(detail(program), { status: 201 });
  }),

  http.patch(
    `${API_BASE_URL}/programs/:programId/courses/:programCourseId`,
    async ({ params, request, cookies }) => {
      const denied = assertDean(cookies);
      if (denied) return denied;
      const program = findProgram(String(params.programId));
      if (!program) return errorResponse(404, 'not_found', 'Program not found.');
      // Scoped to the path's programme — looking it up by id alone would let one
      // programme's URL edit another's curriculum.
      const row = D.program_courses.find(
        (pc) => pc.id === params.programCourseId && pc.program_id === program.id,
      );
      if (!row) return errorResponse(404, 'not_found', 'Curriculum entry not found.');
      const body = (await request.json()) as Partial<DemoProgramCourse>;
      if (body.term_label !== undefined) row.term_label = body.term_label;
      if (body.term_order !== undefined) row.term_order = body.term_order;
      if (body.is_required !== undefined) row.is_required = body.is_required;
      return HttpResponse.json(detail(program));
    },
  ),

  http.delete(
    `${API_BASE_URL}/programs/:programId/courses/:programCourseId`,
    ({ params, cookies }) => {
      const denied = assertDean(cookies);
      if (denied) return denied;
      const program = findProgram(String(params.programId));
      if (!program) return errorResponse(404, 'not_found', 'Program not found.');
      const row = D.program_courses.find(
        (pc) => pc.id === params.programCourseId && pc.program_id === program.id,
      );
      if (!row) return errorResponse(404, 'not_found', 'Curriculum entry not found.');
      D.program_courses = D.program_courses.filter((pc) => pc.id !== row.id);
      return HttpResponse.json(detail(program));
    },
  ),
];
