import { http, HttpResponse } from 'msw';
import { API_BASE_URL } from '@shared/api/client';
import { DEMO_DATASET, DEMO_IDS, getActiveSemester, getActiveYear } from '@shared/api/mocks/demo/dataset';
import type { DemoUser } from '@shared/api/mocks/demo/dataset';
import type { DemoSemester } from '@shared/api/mocks/demo/types';
import { boolParam, errorResponse, listParamsFrom } from './_helpers';
import { paginate } from '@shared/api/mocks/demo/dataset';

/**
 * MSW handlers for the SETTINGS module (api-spec §5.11), backing the ALREADY-BUILT
 * Settings tabs (features/settings/**) with the demo dataset so they render real data
 * offline. Response shapes match the orval-generated models exactly.
 *
 * Endpoints: school profile (GET/PUT), active-term (GET → 200 with the active term),
 * academic years + semesters (GET), activate-semester + archive-year (writes),
 * grading scale (GET/PUT), assessment policy (GET/PUT), users (GET/POST/PATCH),
 * account (GET/PATCH).
 *
 * ⚠️ Module agents: do NOT edit this file — Settings is owned here. The array is wired
 * into handlers/index.ts already.
 */
const D = DEMO_DATASET;

/**
 * Role gate for the academic-structure WRITES, mirroring `require_role(PRINCIPAL)` on
 * the real router.
 *
 * ⚠️ WHY THIS EXISTS. This file used to apply no role checks at all, which hid a real
 * defect for the whole project: `GET /settings/academic-years` was principal/secretary-
 * only on the server, but `useYearFilter` — the staff `?year=` picker — runs on
 * teacher-reachable screens (Grades, Attendance, Classes). Against the live backend a
 * teacher got a 403, the picker silently emptied and no `academic_year_id` was sent;
 * in demo everything looked perfect. The reads are now deliberately open to every
 * authenticated role (that was the fix), so the gate belongs on the writes — and it is
 * here so the demo can no longer certify an authz mismatch as working.
 *
 * The demo has no tokens; the acting role is the `sis_mock_session` cookie auth.ts sets.
 */
function assertPrincipal(cookies: Record<string, string>) {
  const role = cookies['sis_mock_session'] ?? 'principal';
  if (role !== 'principal') {
    return errorResponse(403, 'forbidden', 'Only the principal can change the academic structure.');
  }
  return null;
}

function schoolProfileRead() {
  const p = D.school_profile;
  return {
    name: p.name,
    logo_url: p.logo_url,
    address: p.address,
    contact_email: p.email,
    contact_phone: p.phone,
  };
}

/**
 * D30 §D3/§D6 — the term shape carries `term_type` and the grade-submission deadline,
 * which is now WRITABLE by the Dean. Factored out because three handlers emit it.
 */
function semesterDetail(s: DemoSemester) {
  return {
    id: s.id,
    academic_year_id: s.academic_year_id,
    name: s.name,
    term_type: s.term_type,
    sequence: s.sequence,
    start_date: s.start_date,
    end_date: s.end_date,
    grade_submission_deadline: s.grade_submission_deadline,
    is_active: s.is_active,
  };
}

function academicYearDetail(yearId: string) {
  const y = D.academic_years.find((a) => a.id === yearId)!;
  return {
    id: y.id,
    name: y.name,
    start_date: y.start_date,
    end_date: y.end_date,
    status: y.status,
    archived_at: y.archived_at,
    semesters: D.semesters
      .filter((s) => s.academic_year_id === y.id)
      .sort((a, b) => a.sequence - b.sequence)
      .map(semesterDetail),
  };
}

function gradingScaleRead(yearId: string) {
  const g = D.grading_scales.find((s) => s.academic_year_id === yearId) ?? D.grading_scales[0]!;
  return {
    academic_year_id: g.academic_year_id,
    pass_mark: g.pass_mark,
    is_frozen: g.is_frozen,
    bands: g.bands.map((b) => ({ ...b })),
  };
}

function userListItem(u: DemoUser) {
  return {
    id: u.id,
    email: u.email,
    username: u.username,
    full_name: u.full_name,
    role: u.role,
    is_active: u.is_active,
    must_change_password: u.must_change_password,
    last_login_at: u.last_login_at,
  };
}

export const settingsHandlers = [
  // ── School profile ────────────────────────────────────────────────────────────
  http.get(`${API_BASE_URL}/settings/school`, () => HttpResponse.json(schoolProfileRead())),
  http.put(`${API_BASE_URL}/settings/school`, async ({ request }) => {
    const body = (await request.json()) as {
      name?: string;
      address?: string;
      contact_email?: string;
      contact_phone?: string;
    };
    if (body.name) D.school_profile.name = body.name;
    if (body.address !== undefined) D.school_profile.address = body.address ?? '';
    if (body.contact_email !== undefined) D.school_profile.email = body.contact_email ?? '';
    if (body.contact_phone !== undefined) D.school_profile.phone = body.contact_phone ?? '';
    return HttpResponse.json(schoolProfileRead());
  }),

  // ── Active term ───────────────────────────────────────────────────────────────
  http.get(`${API_BASE_URL}/settings/active-term`, () => {
    const year = getActiveYear();
    const semester = getActiveSemester();
    if (!year || !semester) {
      return errorResponse(409, 'no_active_semester', 'No active academic term is configured.');
    }
    return HttpResponse.json({
      academic_year: { id: year.id, name: year.name, status: year.status },
      semester: {
        id: semester.id,
        name: semester.name,
        sequence: semester.sequence,
        is_active: semester.is_active,
      },
    });
  }),

  // ── Academic years + semesters ──────────────────────────────────────────────────
  // The two READS are intentionally ungated: they are open to every authenticated role
  // on the real server too (widened 2026-07-29), because every period picker in the app
  // is built from them — staff's `?year=` filter and the student's global year·semester
  // switcher, which joins this response's `semesters` to /students/me/years.
  http.get(`${API_BASE_URL}/settings/academic-years`, () =>
    HttpResponse.json({ items: D.academic_years.map((y) => academicYearDetail(y.id)) }),
  ),
  http.get(`${API_BASE_URL}/settings/semesters`, ({ request }) => {
    const url = new URL(request.url);
    const yearId = url.searchParams.get('academic_year_id');
    let rows = D.semesters;
    if (yearId) rows = rows.filter((s) => s.academic_year_id === yearId);
    return HttpResponse.json({ items: rows.map(semesterDetail) });
  }),
  http.patch(`${API_BASE_URL}/settings/semesters/:semesterId/activate`, ({ params, cookies }) => {
    const denied = assertPrincipal(cookies);
    if (denied) return denied;
    const target = D.semesters.find((s) => s.id === params.semesterId);
    if (!target) return errorResponse(404, 'not_found', 'Semester not found.');
    D.semesters.forEach((s) => {
      s.is_active = s.id === target.id;
    });
    return HttpResponse.json(semesterDetail(target));
  }),
  // ── Create an academic year + its terms ──────────────────────────────────────
  //
  // This handler did not exist before D30, so demo mode 404'd on the "New academic
  // year" button while the real backend answered 201 — the mirror image of the defect
  // the file header describes. Added here because the N-term create dialog is the
  // headline of §D3 and has to be demonstrable without a backend.
  http.post(`${API_BASE_URL}/settings/academic-years`, async ({ request, cookies }) => {
    const denied = assertPrincipal(cookies);
    if (denied) return denied;
    const body = (await request.json()) as {
      name: string;
      start_date: string;
      end_date: string;
      semesters: Omit<DemoSemester, 'id' | 'academic_year_id' | 'grade_submission_deadline' | 'is_active'>[];
    };
    if (body.end_date <= body.start_date) {
      return errorResponse(422, 'validation_error', 'Some fields need attention.', {
        end_date: ['Must be after start_date.'],
      });
    }
    if (!body.semesters?.length) {
      return errorResponse(422, 'validation_error', 'Some fields need attention.', {
        semesters: ['At least one term is required.'],
      });
    }
    const sequences = body.semesters.map((t) => t.sequence);
    if (new Set(sequences).size !== sequences.length) {
      return errorResponse(422, 'validation_error', 'Some fields need attention.', {
        semesters: ['Sequence numbers must be distinct.'],
      });
    }
    if (D.academic_years.some((y) => y.status === 'active')) {
      return errorResponse(
        409,
        'active_year_exists',
        'An active academic year already exists; archive it first.',
      );
    }

    const yearId = `ay-new-${D.academic_years.length + 1}`;
    D.academic_years.push({
      id: yearId,
      name: body.name,
      start_date: body.start_date,
      end_date: body.end_date,
      status: 'active',
      archived_at: null,
    });

    // The LOWEST sequence starts active — with N terms, "sequence === 1" is no longer
    // a safe stand-in for "the first one" (a year whose terms start at 2 would have
    // been created with no active term at all).
    const first = Math.min(...sequences);
    D.semesters.forEach((s) => {
      s.is_active = false;
    });
    body.semesters
      .slice()
      .sort((a, b) => a.sequence - b.sequence)
      .forEach((t, i) => {
        D.semesters.push({
          id: `${yearId}-t${i + 1}`,
          academic_year_id: yearId,
          name: t.name,
          term_type: t.term_type ?? 'semester',
          sequence: t.sequence,
          start_date: t.start_date,
          end_date: t.end_date,
          grade_submission_deadline: null,
          is_active: t.sequence === first,
        });
      });

    // Seed the year's grading scale from the existing one, as the service does.
    const template = D.grading_scales[0];
    if (template) {
      D.grading_scales.push({
        academic_year_id: yearId,
        pass_mark: template.pass_mark,
        is_frozen: false,
        bands: template.bands.map((b) => ({ ...b })),
      });
    }

    return HttpResponse.json(academicYearDetail(yearId), { status: 201 });
  }),

  // ── D30 §D3 — add / correct ONE calendar term (Dean only) ─────────────────────
  // New endpoints: before D30 the whole calendar came from creating a year, which made
  // exactly two semesters, so BAJC's Summer and Spring blocks had no route at all.
  http.post(`${API_BASE_URL}/settings/semesters`, async ({ request, cookies }) => {
    const denied = assertPrincipal(cookies);
    if (denied) return denied;
    const body = (await request.json()) as Omit<DemoSemester, 'id' | 'is_active'>;
    const year = D.academic_years.find((y) => y.id === body.academic_year_id);
    if (!year) return errorResponse(404, 'not_found', 'Academic year not found.');
    if (year.status === 'archived') {
      return errorResponse(409, 'year_archived', 'Cannot change the terms of an archived year.');
    }
    if (body.end_date <= body.start_date) {
      return errorResponse(422, 'validation_error', 'Some fields need attention.', {
        end_date: ['Must be after start_date.'],
      });
    }
    if (
      D.semesters.some(
        (s) => s.academic_year_id === year.id && s.sequence === body.sequence,
      )
    ) {
      return errorResponse(
        409,
        'duplicate_semester_sequence',
        `Another term in this year already uses sequence ${body.sequence}.`,
      );
    }
    const created: DemoSemester = {
      id: `sem-new-${D.semesters.length + 1}`,
      academic_year_id: year.id,
      name: body.name,
      term_type: body.term_type ?? 'semester',
      sequence: body.sequence,
      start_date: body.start_date,
      end_date: body.end_date,
      // Optional at creation; absent means the term never closes (D30 §D6).
      grade_submission_deadline: body.grade_submission_deadline ?? null,
      // Created INACTIVE: adding a future block must not move the current term.
      is_active: false,
    };
    D.semesters.push(created);
    return HttpResponse.json(semesterDetail(created), { status: 201 });
  }),

  http.patch(`${API_BASE_URL}/settings/semesters/:semesterId`, async ({ params, request, cookies }) => {
    const denied = assertPrincipal(cookies);
    if (denied) return denied;
    const term = D.semesters.find((s) => s.id === params.semesterId);
    if (!term) return errorResponse(404, 'not_found', 'Semester not found.');
    const body = (await request.json()) as Partial<DemoSemester>;
    // Validated against the MERGED dates, so moving only `start_date` past the stored
    // `end_date` is caught — same rule as the server.
    const start = body.start_date ?? term.start_date;
    const end = body.end_date ?? term.end_date;
    if (end <= start) {
      return errorResponse(422, 'validation_error', 'Some fields need attention.', {
        end_date: ['Must be after start_date.'],
      });
    }
    if (
      body.sequence !== undefined &&
      body.sequence !== term.sequence &&
      D.semesters.some(
        (s) =>
          s.id !== term.id &&
          s.academic_year_id === term.academic_year_id &&
          s.sequence === body.sequence,
      )
    ) {
      return errorResponse(
        409,
        'duplicate_semester_sequence',
        `Another term in this year already uses sequence ${body.sequence}.`,
      );
    }
    if (body.name !== undefined) term.name = body.name;
    if (body.term_type !== undefined) term.term_type = body.term_type;
    if (body.sequence !== undefined) term.sequence = body.sequence;
    // PRESENCE, not None-ness — mirroring the server's `model_fields_set` check. An
    // explicit `null` REOPENS a closed grade window; omitting the key leaves it alone,
    // so renaming a term cannot silently reopen it (D30 §D6).
    if ('grade_submission_deadline' in body) {
      term.grade_submission_deadline = body.grade_submission_deadline ?? null;
    }
    term.start_date = start;
    term.end_date = end;
    return HttpResponse.json(semesterDetail(term));
  }),

  http.post(`${API_BASE_URL}/settings/academic-years/:yearId/archive`, ({ params, cookies }) => {
    const denied = assertPrincipal(cookies);
    if (denied) return denied;
    const year = D.academic_years.find((y) => y.id === params.yearId);
    if (!year) return errorResponse(404, 'not_found', 'Academic year not found.');
    if (year.status === 'archived') {
      return errorResponse(409, 'year_already_archived', 'This year is already archived.');
    }
    return HttpResponse.json(
      { snapshots_written: 0, no_active_year_remaining: false },
      { status: 202 },
    );
  }),

  // ── Grading scale ───────────────────────────────────────────────────────────────
  http.get(`${API_BASE_URL}/settings/grading-scale`, ({ request }) => {
    const url = new URL(request.url);
    const yearId = url.searchParams.get('academic_year_id') ?? DEMO_IDS.activeYearId;
    return HttpResponse.json(gradingScaleRead(yearId));
  }),
  http.put(`${API_BASE_URL}/settings/grading-scale`, async ({ request }) => {
    const body = (await request.json()) as {
      pass_mark?: number;
      bands?: Array<Record<string, unknown>>;
    };
    const scale = D.grading_scales.find((s) => s.academic_year_id === DEMO_IDS.activeYearId)!;
    if (typeof body.pass_mark === 'number') scale.pass_mark = body.pass_mark;
    if (Array.isArray(body.bands)) {
      scale.bands = body.bands.map((b) => ({
        letter: String(b.letter ?? ''),
        min_score: Number(b.min_score ?? 0),
        max_score: Number(b.max_score ?? 0),
        // Round-tripped, and absent/blank stays NULL rather than becoming 0 (D30 §D5).
        // `Number(undefined)` is NaN and `Number(null)` is 0, so neither coercion is
        // safe here — the backend stores NULL for "this scale cannot price this letter",
        // and 0.00 is an F.
        grade_point:
          b.grade_point === null || b.grade_point === undefined || b.grade_point === ''
            ? null
            : Number(b.grade_point),
        is_passing: Boolean(b.is_passing ?? false),
        sort_order: Number(b.sort_order ?? 0),
      }));
    }
    return HttpResponse.json({ ...gradingScaleRead(DEMO_IDS.activeYearId), affects_displayed_grades: true });
  }),

  // ── Assessment policy ────────────────────────────────────────────────────────────
  http.get(`${API_BASE_URL}/settings/assessment-policy`, () =>
    HttpResponse.json({ ...D.assessment_policy }),
  ),
  http.put(`${API_BASE_URL}/settings/assessment-policy`, async ({ request }) => {
    const body = (await request.json()) as Partial<typeof D.assessment_policy>;
    if (typeof body.absent_as_zero === 'boolean') D.assessment_policy.absent_as_zero = body.absent_as_zero;
    if (typeof body.allow_makeup === 'boolean') D.assessment_policy.allow_makeup = body.allow_makeup;
    if (typeof body.drop_lowest_count === 'number')
      D.assessment_policy.drop_lowest_count = body.drop_lowest_count;
    return HttpResponse.json({ ...D.assessment_policy });
  }),

  // ── Users admin ───────────────────────────────────────────────────────────────────
  http.get(`${API_BASE_URL}/settings/users`, ({ request }) => {
    const url = new URL(request.url);
    const role = url.searchParams.get('role');
    const isActive = boolParam(url, 'is_active');
    const search = url.searchParams.get('search');
    let rows = D.users;
    if (role) rows = rows.filter((u) => u.role === role);
    if (isActive !== null) rows = rows.filter((u) => u.is_active === isActive);
    if (search) {
      const q = search.toLowerCase();
      rows = rows.filter(
        (u) => u.full_name.toLowerCase().includes(q) || u.email.toLowerCase().includes(q),
      );
    }
    const page = paginate(
      rows.map(userListItem) as unknown as Array<Record<string, unknown>>,
      { ...listParamsFrom(url), sort: url.searchParams.get('sort') ?? 'full_name' },
    );
    return HttpResponse.json(page);
  }),
  http.post(`${API_BASE_URL}/settings/users`, async ({ request }) => {
    const body = (await request.json()) as {
      email: string;
      username?: string;
      full_name: string;
      role: DemoUser['role'];
      temporary_password?: string;
    };
    if (D.users.some((u) => u.email.toLowerCase() === body.email.toLowerCase())) {
      return errorResponse(409, 'duplicate_email', 'A user with this email already exists.');
    }
    const newUser: DemoUser = {
      id: `user-new-${D.users.length + 1}`,
      email: body.email,
      username: body.username ?? null,
      full_name: body.full_name,
      role: body.role,
      is_active: true,
      must_change_password: true,
      last_login_at: null,
      locale: 'en',
      theme: 'light',
      date_format: null,
      default_page_size: 25,
    };
    D.users.push(newUser);
    return HttpResponse.json(
      { user: userListItem(newUser), temporary_password: body.temporary_password ?? 'Temp-Pass-5678' },
      { status: 201 },
    );
  }),
  http.patch(`${API_BASE_URL}/settings/users/:userId`, async ({ params, request }) => {
    const user = D.users.find((u) => u.id === params.userId);
    if (!user) return errorResponse(404, 'not_found', 'User not found.');
    const body = (await request.json()) as Partial<
      Pick<DemoUser, 'full_name' | 'username' | 'role' | 'is_active'>
    >;
    if (body.full_name !== undefined) user.full_name = body.full_name;
    if (body.username !== undefined) user.username = body.username;
    if (body.role !== undefined) user.role = body.role;
    if (body.is_active !== undefined) user.is_active = body.is_active;
    return HttpResponse.json(userListItem(user));
  }),

  // ── Account / preferences (self) ─────────────────────────────────────────────────
  // The demo resolves "self" from the mock session role cookie (auth.ts) → the matching
  // seeded user. Falls back to the principal.
  http.get(`${API_BASE_URL}/settings/account`, ({ cookies }) => {
    const role = cookies['sis_mock_session'] ?? 'principal';
    const user = D.users.find((u) => u.role === role) ?? D.users[0]!;
    return HttpResponse.json(accountResponse(user));
  }),
  http.patch(`${API_BASE_URL}/settings/account`, async ({ cookies, request }) => {
    const role = cookies['sis_mock_session'] ?? 'principal';
    const user = D.users.find((u) => u.role === role) ?? D.users[0]!;
    const body = (await request.json()) as {
      full_name?: string;
      preferences?: {
        locale?: string;
        theme?: string;
        date_format?: string;
        default_page_size?: number;
      };
    };
    if (body.full_name) user.full_name = body.full_name;
    if (body.preferences) {
      const p = body.preferences;
      if (p.locale !== undefined) user.locale = p.locale;
      if (p.theme !== undefined) user.theme = p.theme;
      if (p.date_format !== undefined) user.date_format = p.date_format;
      if (p.default_page_size !== undefined) user.default_page_size = p.default_page_size;
    }
    return HttpResponse.json(accountResponse(user));
  }),
];

function accountResponse(u: DemoUser) {
  return {
    id: u.id,
    email: u.email,
    username: u.username,
    full_name: u.full_name,
    role: u.role,
    must_change_password: u.must_change_password,
    is_active: u.is_active,
    preferences: {
      locale: u.locale,
      theme: u.theme,
      date_format: u.date_format,
      default_page_size: u.default_page_size,
    },
  };
}
