import { http, HttpResponse } from 'msw';
import { API_BASE_URL } from '@shared/api/client';
import { DEMO_DATASET, listSubjects } from '@shared/api/mocks/demo/dataset';
import type { DemoSubject } from '@shared/api/mocks/demo/dataset';
import { boolParam, errorResponse, listParamsFrom } from './_helpers';

/**
 * MSW handlers for the SUBJECTS catalog (api-spec §5b), backing the ALREADY-BUILT
 * Settings › Subjects screen (features/settings/SubjectsPage.tsx). Response shapes
 * match the orval-generated models (PageSubjectListItem / SubjectDetail).
 *
 * Endpoints: GET /subjects (paginated picker/catalog), POST/PATCH/DELETE with the
 * documented 409 guards (duplicate name/code, subject in use).
 *
 * ⚠️ Module agents: do NOT edit this file — the Subjects catalog is owned here. The
 * array is wired into handlers/index.ts already.
 */
const D = DEMO_DATASET;

function toListItem(s: DemoSubject) {
  return { id: s.id, name: s.name, code: s.code, is_active: s.is_active };
}

export const subjectsHandlers = [
  http.get(`${API_BASE_URL}/subjects`, ({ request }) => {
    const url = new URL(request.url);
    const page = listSubjects({
      ...listParamsFrom(url),
      is_active: boolParam(url, 'is_active'),
    });
    return HttpResponse.json({ ...page, items: page.items.map(toListItem) });
  }),

  http.post(`${API_BASE_URL}/subjects`, async ({ request }) => {
    const body = (await request.json()) as { name: string; code?: string };
    if (D.subjects.some((s) => s.name.toLowerCase() === body.name.toLowerCase())) {
      return errorResponse(409, 'duplicate_subject_name', 'A subject with this name already exists.');
    }
    if (body.code && D.subjects.some((s) => s.code.toLowerCase() === body.code!.toLowerCase())) {
      return errorResponse(409, 'duplicate_subject_code', 'A subject with this code already exists.');
    }
    const created: DemoSubject = {
      id: `subj-new-${D.subjects.length + 1}`,
      name: body.name,
      code: body.code ?? '',
      is_active: true,
    };
    D.subjects.push(created);
    return HttpResponse.json(toListItem(created), { status: 201 });
  }),

  http.patch(`${API_BASE_URL}/subjects/:subjectId`, async ({ params, request }) => {
    const subject = D.subjects.find((s) => s.id === params.subjectId);
    if (!subject) return errorResponse(404, 'not_found', 'Subject not found.');
    const body = (await request.json()) as { name?: string; code?: string; is_active?: boolean };
    if (body.name && D.subjects.some((s) => s.id !== subject.id && s.name.toLowerCase() === body.name!.toLowerCase())) {
      return errorResponse(409, 'duplicate_subject_name', 'A subject with this name already exists.');
    }
    if (body.code && D.subjects.some((s) => s.id !== subject.id && s.code.toLowerCase() === body.code!.toLowerCase())) {
      return errorResponse(409, 'duplicate_subject_code', 'A subject with this code already exists.');
    }
    if (body.name !== undefined) subject.name = body.name;
    if (body.code !== undefined) subject.code = body.code ?? '';
    if (body.is_active !== undefined) subject.is_active = body.is_active;
    return HttpResponse.json(toListItem(subject));
  }),

  http.delete(`${API_BASE_URL}/subjects/:subjectId`, ({ params }) => {
    const subject = D.subjects.find((s) => s.id === params.subjectId);
    if (!subject) return errorResponse(404, 'not_found', 'Subject not found.');
    const inUse = D.class_subjects.some((cs) => cs.subject_id === subject.id);
    if (inUse) {
      return errorResponse(
        409,
        'subject_in_use',
        'Taught in one or more sections — retire it instead.',
      );
    }
    D.subjects = D.subjects.filter((s) => s.id !== subject.id);
    return new HttpResponse(null, { status: 204 });
  }),
];
