"""initial schema — 28 tables, enums, indexes + Supabase RLS/REVOKE baseline

Builds the full SIS schema from database-schema.md (§3 tables, §5 constraints,
§6 indexes, §11 ordering) plus the Supabase security baseline required by the
7.0b workstream (default-deny RLS on every public table + REVOKE from anon /
authenticated). Hand-authored (not autogenerated) for deterministic enum-type
ordering and exact constraint/index parity with the ORM.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-06-27

KEY DESIGN NOTES
----------------
* Enum strategy (schema §1.5): nine NATIVE Postgres enums created explicitly,
  in order, BEFORE any table that uses them. The ORM columns use
  `create_type=False` (app/db/types.py), so the migration owns type lifecycle.
* PK strategy (DB-1/DB-2): business tables use `uuid` PK defaulting to
  `gen_random_uuid()` (pgcrypto); `audit_log` is the sole `bigint identity`.
* Soft-delete uniqueness (§8): natural keys use partial unique indexes
  `WHERE deleted_at IS NULL`. One-active invariants (academic_years/semesters)
  and singletons use partial / pinned-id constraints.
* `updated_at` backstop trigger (§7): a single `set_updated_at()` function +
  per-table BEFORE UPDATE triggers keep `updated_at` current even for raw SQL.
* SECURITY BASELINE (this workstream): RLS here is a PostgREST-surface lockdown,
  NOT a substitute for app-layer authz. The backend connects as the `postgres`
  table OWNER, which BYPASSES RLS, so app-layer RBAC/ownership helpers remain the
  real authorization. Enabling RLS with NO policies (default-deny) + revoking
  privileges from `anon`/`authenticated` shuts the auto-exposed PostgREST API
  surface over student PII. The REVOKE is wrapped in a portability guard so this
  migration also runs on a non-Supabase Postgres where those roles don't exist.
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql as pg

# revision identifiers, used by Alembic.
revision: str = "0001_initial_schema"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ── Enum types (schema §1.5) — name -> ordered labels ─────────────────────────
ENUMS: dict[str, tuple[str, ...]] = {
    "user_role": ("principal", "secretary", "teacher", "student"),
    "student_status": ("active", "inactive", "transferred", "graduated", "withdrawn"),
    "teacher_status": ("active", "inactive"),
    "academic_year_status": ("active", "archived"),
    "assessment_type": ("quiz", "test", "exam", "assignment"),
    "assessment_status": ("draft", "published", "grading", "graded"),
    "grade_status": ("pending", "graded", "absent", "excused", "exempt"),
    "attendance_status": ("present", "absent", "late", "excused"),
    "announcement_audience": ("all", "students", "teachers", "class"),
}

# Every table created here (FK-dependency order). Reused for the RLS loop and the
# reverse-order downgrade so the two stay in lockstep.
ALL_TABLES: tuple[str, ...] = (
    "users",
    "user_preferences",
    "refresh_sessions",
    "password_reset_tokens",
    "login_attempts",
    "assessment_policies",
    "academic_years",
    "semesters",
    "grading_scales",
    "grading_scale_bands",
    "subjects",
    "teacher_profiles",
    "student_profiles",
    "classes",
    "class_subjects",
    "class_teachers",
    "class_enrollments",
    "assessment_categories",
    "assessments",
    "assessment_grades",
    "term_grade_snapshots",
    "attendance_records",
    "announcements",
    "announcement_reads",
    "student_documents",
    "report_card_snapshots",
    "school_profile",
    "audit_log",
)


def _enum(name: str) -> pg.ENUM:
    """Reference an already-created native enum (do not re-create the type)."""
    return pg.ENUM(*ENUMS[name], name=name, create_type=False)


# Mixin column shortcuts (schema §1.3–1.4) -------------------------------------
def _ts_cols() -> list[sa.Column]:
    return [
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
    ]


def _audit_cols() -> list[sa.Column]:
    return [
        sa.Column("created_by", pg.UUID(as_uuid=True),
                  sa.ForeignKey("users.id", ondelete="SET NULL"), nullable=True),
        sa.Column("updated_by", pg.UUID(as_uuid=True),
                  sa.ForeignKey("users.id", ondelete="SET NULL"), nullable=True),
    ]


def _soft_delete_col() -> sa.Column:
    return sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)


def _uuid_pk() -> sa.Column:
    return sa.Column("id", pg.UUID(as_uuid=True), primary_key=True,
                     server_default=sa.text("gen_random_uuid()"))


# ──────────────────────────────────────────────────────────────────────────────
def upgrade() -> None:
    bind = op.get_bind()

    # 1) Extensions (schema §11) ------------------------------------------------
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto;")
    op.execute("CREATE EXTENSION IF NOT EXISTS citext;")

    # 2) Enum types — explicit, before any table (schema §1.5/§11) -------------
    for name, labels in ENUMS.items():
        pg.ENUM(*labels, name=name).create(bind, checkfirst=True)

    # 3) Tables — FK-dependency order (schema §11) -----------------------------

    # --- Identity / RBAC ------------------------------------------------------
    op.create_table(
        "users",
        _uuid_pk(),
        sa.Column("email", pg.CITEXT(), nullable=False),
        sa.Column("username", pg.CITEXT(), nullable=True),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("role", _enum("user_role"), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("must_change_password", sa.Boolean(), nullable=False,
                  server_default=sa.text("false")),
        sa.Column("failed_login_count", sa.SmallInteger(), nullable=False,
                  server_default=sa.text("0")),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        *_ts_cols(), *_audit_cols(), _soft_delete_col(),
        sa.PrimaryKeyConstraint("id", name="pk_users"),
        sa.CheckConstraint("failed_login_count >= 0", name="ck_users_failed_login_nonneg"),
    )
    op.create_index("uq_users_email", "users", ["email"], unique=True,
                    postgresql_where=sa.text("deleted_at IS NULL"))
    op.create_index("uq_users_username", "users", ["username"], unique=True,
                    postgresql_where=sa.text("deleted_at IS NULL AND username IS NOT NULL"))

    op.create_table(
        "user_preferences",
        sa.Column("user_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("users.id", ondelete="CASCADE", name="fk_user_preferences_user"),
                  primary_key=True),
        sa.Column("locale", sa.Text(), nullable=False, server_default=sa.text("'en'")),
        sa.Column("theme", sa.Text(), nullable=False, server_default=sa.text("'light'")),
        sa.Column("date_format", sa.Text(), nullable=True),
        sa.Column("default_page_size", sa.SmallInteger(), nullable=False,
                  server_default=sa.text("25")),
        *_ts_cols(),
        sa.PrimaryKeyConstraint("user_id", name="pk_user_preferences"),
        sa.CheckConstraint("default_page_size BETWEEN 5 AND 200",
                           name="ck_user_preferences_page_size"),
    )

    op.create_table(
        "refresh_sessions",
        _uuid_pk(),
        sa.Column("user_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("users.id", ondelete="CASCADE", name="fk_refresh_sessions_user"),
                  nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("ip_address", pg.INET(), nullable=True),
        *_ts_cols(),
    )
    op.create_index("uq_refresh_sessions_token_hash", "refresh_sessions",
                    ["token_hash"], unique=True)
    op.create_index("ix_refresh_sessions_user", "refresh_sessions", ["user_id"],
                    postgresql_where=sa.text("is_revoked = false"))

    op.create_table(
        "password_reset_tokens",
        _uuid_pk(),
        sa.Column("user_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("users.id", ondelete="CASCADE", name="fk_pwreset_user"),
                  nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", pg.UUID(as_uuid=True),
                  sa.ForeignKey("users.id", ondelete="SET NULL", name="fk_pwreset_creator"),
                  nullable=True),
        *_ts_cols(),
    )
    op.create_index("uq_pwreset_token_hash", "password_reset_tokens",
                    ["token_hash"], unique=True)

    op.create_table(
        "login_attempts",
        _uuid_pk(),
        sa.Column("email_attempted", pg.CITEXT(), nullable=False),
        sa.Column("user_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("users.id", ondelete="SET NULL", name="fk_login_attempts_user"),
                  nullable=True),
        sa.Column("succeeded", sa.Boolean(), nullable=False),
        sa.Column("ip_address", pg.INET(), nullable=True),
        sa.Column("attempted_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
    )

    # --- Grading policy + academic config -------------------------------------
    op.create_table(
        "assessment_policies",
        sa.Column("id", sa.SmallInteger(), primary_key=True, server_default=sa.text("1")),
        sa.Column("absent_as_zero", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("allow_makeup", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("drop_lowest_count", sa.SmallInteger(), nullable=False,
                  server_default=sa.text("0")),
        *_ts_cols(), *_audit_cols(),
        sa.CheckConstraint("id = 1", name="ck_assessment_policies_singleton"),
        sa.CheckConstraint("drop_lowest_count >= 0", name="ck_assessment_policies_drop_nonneg"),
    )

    op.create_table(
        "academic_years",
        _uuid_pk(),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("status", _enum("academic_year_status"), nullable=False,
                  server_default=sa.text("'active'")),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("absent_as_zero", sa.Boolean(), nullable=True),
        sa.Column("allow_makeup", sa.Boolean(), nullable=True),
        sa.Column("drop_lowest_count", sa.SmallInteger(), nullable=True),
        *_ts_cols(), *_audit_cols(),
        sa.CheckConstraint("end_date > start_date", name="ck_academic_years_dates"),
        sa.CheckConstraint("drop_lowest_count IS NULL OR drop_lowest_count >= 0",
                           name="ck_academic_years_drop_nonneg"),
    )
    op.create_index("uq_academic_years_name", "academic_years", ["name"], unique=True)
    op.create_index("uq_academic_years_one_active", "academic_years", ["status"],
                    unique=True, postgresql_where=sa.text("status = 'active'"))

    op.create_table(
        "semesters",
        _uuid_pk(),
        sa.Column("academic_year_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("academic_years.id", ondelete="RESTRICT", name="fk_semesters_year"),
                  nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("sequence", sa.SmallInteger(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        *_ts_cols(),
        sa.CheckConstraint("sequence IN (1,2)", name="ck_semesters_sequence"),
        sa.CheckConstraint("end_date > start_date", name="ck_semesters_dates"),
    )
    op.create_index("uq_semesters_year_seq", "semesters",
                    ["academic_year_id", "sequence"], unique=True)
    op.create_index("uq_semesters_one_active", "semesters", ["is_active"],
                    unique=True, postgresql_where=sa.text("is_active"))

    op.create_table(
        "grading_scales",
        _uuid_pk(),
        sa.Column("academic_year_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("academic_years.id", ondelete="RESTRICT",
                                name="fk_grading_scales_year"), nullable=False),
        sa.Column("pass_mark", sa.Numeric(5, 2), nullable=False, server_default=sa.text("60.00")),
        sa.Column("is_frozen", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        *_ts_cols(), *_audit_cols(),
        sa.CheckConstraint("pass_mark BETWEEN 0 AND 100", name="ck_grading_scales_passmark"),
    )
    op.create_index("uq_grading_scales_year", "grading_scales",
                    ["academic_year_id"], unique=True)

    op.create_table(
        "grading_scale_bands",
        _uuid_pk(),
        sa.Column("grading_scale_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("grading_scales.id", ondelete="CASCADE", name="fk_bands_scale"),
                  nullable=False),
        sa.Column("letter", sa.Text(), nullable=False),
        sa.Column("min_score", sa.Numeric(5, 2), nullable=False),
        sa.Column("max_score", sa.Numeric(5, 2), nullable=False),
        sa.Column("is_passing", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("sort_order", sa.SmallInteger(), nullable=False),
        *_ts_cols(),
        sa.CheckConstraint("min_score >= 0 AND max_score <= 100 AND min_score <= max_score",
                           name="ck_bands_range"),
    )
    op.create_index("uq_bands_scale_letter", "grading_scale_bands",
                    ["grading_scale_id", "letter"], unique=True)

    # --- Catalog + people -----------------------------------------------------
    op.create_table(
        "subjects",
        _uuid_pk(),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("code", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        *_ts_cols(), _soft_delete_col(),
    )
    op.create_index("uq_subjects_name", "subjects", ["name"], unique=True,
                    postgresql_where=sa.text("deleted_at IS NULL"))
    op.create_index("uq_subjects_code", "subjects", ["code"], unique=True,
                    postgresql_where=sa.text("deleted_at IS NULL AND code IS NOT NULL"))

    op.create_table(
        "teacher_profiles",
        _uuid_pk(),
        sa.Column("user_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("users.id", ondelete="SET NULL", name="fk_teacher_profiles_user"),
                  nullable=True),
        sa.Column("staff_number", sa.Text(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("email", pg.CITEXT(), nullable=True),
        sa.Column("phone", sa.Text(), nullable=True),
        sa.Column("status", _enum("teacher_status"), nullable=False,
                  server_default=sa.text("'active'")),
        sa.Column("subject_specializations", pg.ARRAY(sa.Text()), nullable=True,
                  server_default=sa.text("'{}'")),
        *_ts_cols(), *_audit_cols(), _soft_delete_col(),
    )
    op.create_index("uq_teacher_profiles_user", "teacher_profiles", ["user_id"],
                    unique=True, postgresql_where=sa.text("user_id IS NOT NULL"))
    op.create_index("uq_teacher_profiles_number", "teacher_profiles", ["staff_number"],
                    unique=True, postgresql_where=sa.text("deleted_at IS NULL"))
    op.create_index("ix_teacher_subject_specializations", "teacher_profiles",
                    ["subject_specializations"], postgresql_using="gin")

    op.create_table(
        "student_profiles",
        _uuid_pk(),
        sa.Column("user_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("users.id", ondelete="SET NULL", name="fk_student_profiles_user"),
                  nullable=True),
        sa.Column("student_number", sa.Text(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("gender", sa.Text(), nullable=True),
        sa.Column("enrollment_date", sa.Date(), nullable=False),
        sa.Column("status", _enum("student_status"), nullable=False,
                  server_default=sa.text("'active'")),
        sa.Column("guardian_name", sa.Text(), nullable=True),
        sa.Column("guardian_phone", sa.Text(), nullable=True),
        sa.Column("guardian_email", pg.CITEXT(), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("phone", sa.Text(), nullable=True),
        *_ts_cols(), *_audit_cols(), _soft_delete_col(),
    )
    op.create_index("uq_student_profiles_user", "student_profiles", ["user_id"],
                    unique=True, postgresql_where=sa.text("user_id IS NOT NULL"))
    op.create_index("uq_student_profiles_number", "student_profiles", ["student_number"],
                    unique=True, postgresql_where=sa.text("deleted_at IS NULL"))

    # --- Academic structure (D23 section model) -------------------------------
    op.create_table(
        "classes",
        _uuid_pk(),
        sa.Column("academic_year_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("academic_years.id", ondelete="RESTRICT", name="fk_classes_year"),
                  nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("grade_level", sa.Text(), nullable=False),
        sa.Column("section", sa.Text(), nullable=True),
        sa.Column("capacity", sa.SmallInteger(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        *_ts_cols(), *_audit_cols(), _soft_delete_col(),
        sa.CheckConstraint("capacity IS NULL OR capacity > 0", name="ck_classes_capacity"),
    )
    op.create_index("uq_classes_year_name", "classes", ["academic_year_id", "name"],
                    unique=True, postgresql_where=sa.text("deleted_at IS NULL"))

    op.create_table(
        "class_subjects",
        _uuid_pk(),
        sa.Column("class_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("classes.id", ondelete="RESTRICT", name="fk_class_subjects_class"),
                  nullable=False),
        sa.Column("subject_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("subjects.id", ondelete="RESTRICT",
                                name="fk_class_subjects_subject"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        *_ts_cols(), *_audit_cols(), _soft_delete_col(),
    )
    op.create_index("uq_class_subjects_class_subject", "class_subjects",
                    ["class_id", "subject_id"], unique=True,
                    postgresql_where=sa.text("deleted_at IS NULL"))
    op.create_index("ix_class_subjects_class", "class_subjects", ["class_id"],
                    postgresql_where=sa.text("deleted_at IS NULL"))
    op.create_index("ix_class_subjects_subject", "class_subjects", ["subject_id"],
                    postgresql_where=sa.text("deleted_at IS NULL"))

    op.create_table(
        "class_teachers",
        _uuid_pk(),
        sa.Column("class_subject_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("class_subjects.id", ondelete="CASCADE",
                                name="fk_class_teachers_class_subject"), nullable=False),
        sa.Column("teacher_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("teacher_profiles.id", ondelete="RESTRICT",
                                name="fk_class_teachers_teacher"), nullable=False),
        sa.Column("is_lead", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        *_ts_cols(), *_audit_cols(),
    )
    op.create_index("uq_class_teachers_class_subject_teacher", "class_teachers",
                    ["class_subject_id", "teacher_id"], unique=True)
    op.create_index("ix_class_teachers_teacher", "class_teachers", ["teacher_id"])

    op.create_table(
        "class_enrollments",
        _uuid_pk(),
        sa.Column("class_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("classes.id", ondelete="RESTRICT", name="fk_enroll_class"),
                  nullable=False),
        sa.Column("student_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("student_profiles.id", ondelete="RESTRICT",
                                name="fk_enroll_student"), nullable=False),
        sa.Column("semester_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("semesters.id", ondelete="RESTRICT", name="fk_enroll_semester"),
                  nullable=False),
        sa.Column("enrolled_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.Column("unenrolled_at", sa.DateTime(timezone=True), nullable=True),
        *_ts_cols(), *_audit_cols(),
    )
    op.create_index("uq_enroll_active", "class_enrollments",
                    ["class_id", "student_id", "semester_id"], unique=True,
                    postgresql_where=sa.text("unenrolled_at IS NULL"))
    op.create_index("ix_enroll_class_semester", "class_enrollments",
                    ["class_id", "semester_id"],
                    postgresql_where=sa.text("unenrolled_at IS NULL"))
    op.create_index("ix_enroll_student", "class_enrollments", ["student_id"])

    # --- Assessment / grading -------------------------------------------------
    op.create_table(
        "assessment_categories",
        _uuid_pk(),
        sa.Column("class_subject_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("class_subjects.id", ondelete="CASCADE",
                                name="fk_categories_class_subject"), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("weight", sa.Numeric(5, 2), nullable=False),
        sa.Column("absent_as_zero", sa.Boolean(), nullable=True),
        sa.Column("allow_makeup", sa.Boolean(), nullable=True),
        sa.Column("drop_lowest_count", sa.SmallInteger(), nullable=True),
        *_ts_cols(), *_audit_cols(),
        sa.CheckConstraint("weight >= 0", name="ck_categories_weight"),
        sa.CheckConstraint("drop_lowest_count IS NULL OR drop_lowest_count >= 0",
                           name="ck_categories_drop_nonneg"),
    )
    op.create_index("uq_categories_class_subject_name", "assessment_categories",
                    ["class_subject_id", "name"], unique=True)

    op.create_table(
        "assessments",
        _uuid_pk(),
        sa.Column("class_subject_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("class_subjects.id", ondelete="RESTRICT",
                                name="fk_assessments_class_subject"), nullable=False),
        sa.Column("semester_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("semesters.id", ondelete="RESTRICT", name="fk_assessments_semester"),
                  nullable=False),
        sa.Column("category_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("assessment_categories.id", ondelete="SET NULL",
                                name="fk_assessments_category"), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("type", _enum("assessment_type"), nullable=False),
        sa.Column("max_score", sa.Numeric(6, 2), nullable=False),
        sa.Column("weight", sa.Numeric(5, 2), nullable=False, server_default=sa.text("1.00")),
        sa.Column("assessment_date", sa.Date(), nullable=True),
        sa.Column("status", _enum("assessment_status"), nullable=False,
                  server_default=sa.text("'draft'")),
        sa.Column("is_released", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("absent_as_zero", sa.Boolean(), nullable=True),
        sa.Column("allow_makeup", sa.Boolean(), nullable=True),
        sa.Column("drop_lowest_count", sa.SmallInteger(), nullable=True),
        *_ts_cols(), *_audit_cols(), _soft_delete_col(),
        sa.CheckConstraint("max_score > 0", name="ck_assessments_maxscore"),
        sa.CheckConstraint("weight >= 0", name="ck_assessments_weight"),
        sa.CheckConstraint("drop_lowest_count IS NULL OR drop_lowest_count >= 0",
                           name="ck_assessments_drop_nonneg"),
    )
    op.create_index("ix_assessments_class_subject_semester", "assessments",
                    ["class_subject_id", "semester_id"],
                    postgresql_where=sa.text("deleted_at IS NULL"))

    op.create_table(
        "assessment_grades",
        _uuid_pk(),
        sa.Column("assessment_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("assessments.id", ondelete="RESTRICT", name="fk_grades_assessment"),
                  nullable=False),
        sa.Column("student_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("student_profiles.id", ondelete="RESTRICT",
                                name="fk_grades_student"), nullable=False),
        sa.Column("enrollment_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("class_enrollments.id", ondelete="RESTRICT",
                                name="fk_grades_enrollment"), nullable=False),
        sa.Column("status", _enum("grade_status"), nullable=False,
                  server_default=sa.text("'pending'")),
        sa.Column("score", sa.Numeric(6, 2), nullable=True),
        sa.Column("makeup_score", sa.Numeric(6, 2), nullable=True),
        sa.Column("is_released", sa.Boolean(), nullable=True),
        sa.Column("graded_at", sa.DateTime(timezone=True), nullable=True),
        *_ts_cols(), *_audit_cols(),
        sa.CheckConstraint(
            "(status = 'graded' AND score IS NOT NULL) "
            "OR (status <> 'graded' AND score IS NULL)",
            name="ck_grades_score_when_graded"),
        sa.CheckConstraint("score IS NULL OR score >= 0", name="ck_grades_score_nonneg"),
        sa.CheckConstraint("makeup_score IS NULL OR makeup_score >= 0",
                           name="ck_grades_makeup_nonneg"),
    )
    op.create_index("uq_grades_assessment_student", "assessment_grades",
                    ["assessment_id", "student_id"], unique=True)
    op.create_index("ix_grades_student", "assessment_grades", ["student_id"])

    op.create_table(
        "term_grade_snapshots",
        _uuid_pk(),
        sa.Column("student_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("student_profiles.id", ondelete="RESTRICT",
                                name="fk_term_snapshot_student"), nullable=False),
        sa.Column("class_subject_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("class_subjects.id", ondelete="RESTRICT",
                                name="fk_term_snapshot_class_subject"), nullable=False),
        sa.Column("semester_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("semesters.id", ondelete="RESTRICT",
                                name="fk_term_snapshot_semester"), nullable=False),
        sa.Column("subject_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("subjects.id", ondelete="RESTRICT",
                                name="fk_term_snapshot_subject"), nullable=False),
        sa.Column("numeric_grade", sa.Numeric(6, 2), nullable=False),
        sa.Column("letter_grade", sa.Text(), nullable=False),
        sa.Column("weight_base_used", sa.Numeric(6, 2), nullable=True),
        sa.Column("effective_policy", pg.JSONB(), nullable=False,
                  server_default=sa.text("'{}'::jsonb")),
        sa.Column("frozen_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        *_ts_cols(),
    )
    op.create_index("uq_term_snapshot", "term_grade_snapshots",
                    ["student_id", "class_subject_id", "semester_id"], unique=True)
    op.create_index("ix_term_snapshot_student", "term_grade_snapshots", ["student_id"])

    # --- Attendance -----------------------------------------------------------
    op.create_table(
        "attendance_records",
        _uuid_pk(),
        sa.Column("class_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("classes.id", ondelete="RESTRICT", name="fk_attendance_class"),
                  nullable=False),
        sa.Column("student_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("student_profiles.id", ondelete="RESTRICT",
                                name="fk_attendance_student"), nullable=False),
        sa.Column("enrollment_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("class_enrollments.id", ondelete="RESTRICT",
                                name="fk_attendance_enrollment"), nullable=False),
        sa.Column("semester_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("semesters.id", ondelete="RESTRICT", name="fk_attendance_semester"),
                  nullable=False),
        sa.Column("attendance_date", sa.Date(), nullable=False),
        sa.Column("status", _enum("attendance_status"), nullable=False,
                  server_default=sa.text("'present'")),
        *_ts_cols(), *_audit_cols(),
    )
    op.create_index("uq_attendance_class_student_date", "attendance_records",
                    ["class_id", "student_id", "attendance_date"], unique=True)
    op.create_index("ix_attendance_class_date", "attendance_records",
                    ["class_id", "attendance_date"])
    op.create_index("ix_attendance_student_semester", "attendance_records",
                    ["student_id", "semester_id"])

    # --- Communications -------------------------------------------------------
    op.create_table(
        "announcements",
        _uuid_pk(),
        sa.Column("author_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("users.id", ondelete="SET NULL", name="fk_announcements_author"),
                  nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("audience", _enum("announcement_audience"), nullable=False),
        sa.Column("class_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("classes.id", ondelete="CASCADE", name="fk_announcements_class"),
                  nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        *_ts_cols(), *_audit_cols(), _soft_delete_col(),
        sa.CheckConstraint("(audience = 'class') = (class_id IS NOT NULL)",
                           name="ck_announcements_class_audience"),
    )
    op.create_index("ix_announcements_published", "announcements",
                    [sa.text("published_at DESC")],
                    postgresql_where=sa.text("deleted_at IS NULL"))
    op.create_index("ix_announcements_class", "announcements", ["class_id"],
                    postgresql_where=sa.text("class_id IS NOT NULL"))
    op.create_index("ix_announcements_audience", "announcements", ["audience"])

    op.create_table(
        "announcement_reads",
        sa.Column("announcement_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("announcements.id", ondelete="CASCADE",
                                name="fk_announcement_reads_ann"), primary_key=True),
        sa.Column("user_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("users.id", ondelete="CASCADE",
                                name="fk_announcement_reads_user"), primary_key=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
    )
    op.create_index("ix_announcement_reads_user", "announcement_reads", ["user_id"])

    # --- Documents / reports --------------------------------------------------
    op.create_table(
        "student_documents",
        _uuid_pk(),
        sa.Column("student_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("student_profiles.id", ondelete="RESTRICT",
                                name="fk_student_documents_student"), nullable=False),
        sa.Column("file_name", sa.Text(), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("content_type", sa.Text(), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("document_type", sa.Text(), nullable=True),
        *_ts_cols(), *_audit_cols(), _soft_delete_col(),
    )
    op.create_index("uq_student_documents_key", "student_documents",
                    ["storage_key"], unique=True)

    op.create_table(
        "report_card_snapshots",
        _uuid_pk(),
        sa.Column("student_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("student_profiles.id", ondelete="RESTRICT",
                                name="fk_report_card_student"), nullable=False),
        sa.Column("semester_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("semesters.id", ondelete="RESTRICT", name="fk_report_card_semester"),
                  nullable=False),
        sa.Column("payload", pg.JSONB(), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=True),
        sa.Column("frozen_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        *_ts_cols(),
    )
    op.create_index("uq_report_card_snapshot", "report_card_snapshots",
                    ["student_id", "semester_id"], unique=True)

    # --- System ---------------------------------------------------------------
    op.create_table(
        "school_profile",
        sa.Column("id", sa.SmallInteger(), primary_key=True, server_default=sa.text("1")),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("logo_storage_key", sa.Text(), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("contact_email", pg.CITEXT(), nullable=True),
        sa.Column("contact_phone", sa.Text(), nullable=True),
        *_ts_cols(), *_audit_cols(),
        sa.CheckConstraint("id = 1", name="ck_school_profile_singleton"),
    )

    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), primary_key=True),
        sa.Column("actor_user_id", pg.UUID(as_uuid=True),
                  sa.ForeignKey("users.id", ondelete="SET NULL", name="fk_audit_actor"),
                  nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("entity_type", sa.Text(), nullable=False),
        sa.Column("entity_id", pg.UUID(as_uuid=True), nullable=True),
        sa.Column("summary", pg.JSONB(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
    )

    # 4) updated_at backstop trigger (schema §7) -------------------------------
    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    for table in _tables_with_updated_at():
        op.execute(
            f'CREATE TRIGGER trg_{table}_updated_at BEFORE UPDATE ON "{table}" '
            f"FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
        )

    # 5) SECURITY BASELINE — PostgREST-surface lockdown (this workstream) -------
    #    RLS here is NOT a substitute for app-layer authz. The app connects as the
    #    table-OWNER (`postgres`) which BYPASSES RLS; default-deny RLS (no policies)
    #    + REVOKE only shut the auto-exposed anon/authenticated PostgREST surface.
    #    See module docstring.
    for table in ALL_TABLES:
        op.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY;')
        # FORCE so even a future non-owner table-owner-equivalent is covered; the
        # `postgres` superuser/owner still bypasses, which is intended.
        op.execute(f'ALTER TABLE "{table}" FORCE ROW LEVEL SECURITY;')

    # Defense-in-depth REVOKE, portable to a non-Supabase PG (roles may not exist).
    op.execute(
        """
        DO $$
        DECLARE r text;
        BEGIN
            FOREACH r IN ARRAY ARRAY['anon', 'authenticated'] LOOP
                IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN
                    EXECUTE format('REVOKE ALL ON ALL TABLES IN SCHEMA public FROM %I', r);
                    EXECUTE format('REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM %I', r);
                    EXECUTE format('REVOKE ALL ON ALL FUNCTIONS IN SCHEMA public FROM %I', r);
                    -- Future objects created by this role won't auto-grant to them.
                    EXECUTE format(
                        'ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM %I', r);
                    EXECUTE format(
                        'ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM %I', r);
                END IF;
            END LOOP;
        END $$;
        """
    )


def downgrade() -> None:
    bind = op.get_bind()

    # Reverse the security baseline first (so DROP TABLE is unencumbered) --------
    op.execute(
        """
        DO $$
        DECLARE r text;
        BEGIN
            FOREACH r IN ARRAY ARRAY['anon', 'authenticated'] LOOP
                IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN
                    EXECUTE format(
                        'ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO %I', r);
                    EXECUTE format(
                        'ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO %I', r);
                END IF;
            END LOOP;
        END $$;
        """
    )
    # RLS is disabled implicitly by DROP TABLE; explicit disable kept tidy.
    for table in ALL_TABLES:
        op.execute(f'ALTER TABLE IF EXISTS "{table}" NO FORCE ROW LEVEL SECURITY;')
        op.execute(f'ALTER TABLE IF EXISTS "{table}" DISABLE ROW LEVEL SECURITY;')

    # Drop triggers + function ---------------------------------------------------
    for table in _tables_with_updated_at():
        op.execute(f'DROP TRIGGER IF EXISTS trg_{table}_updated_at ON "{table}";')
    op.execute("DROP FUNCTION IF EXISTS set_updated_at();")

    # Drop tables in reverse FK-dependency order --------------------------------
    for table in reversed(ALL_TABLES):
        op.drop_table(table)

    # Drop enum types last (nothing references them now) ------------------------
    for name in ENUMS:
        pg.ENUM(name=name).drop(bind, checkfirst=True)

    # Extensions are intentionally NOT dropped — they may be shared by other
    # schemas/objects in the same Supabase database, and dropping pgcrypto/citext
    # could break unrelated state. They are harmless if left installed.


def _tables_with_updated_at() -> tuple[str, ...]:
    """Tables carrying TimestampMixin (have an updated_at column) — every table
    EXCEPT the three that omit it: login_attempts, announcement_reads, audit_log
    (append-only / read-ledger rows, schema §3)."""
    no_updated_at = {"login_attempts", "announcement_reads", "audit_log"}
    return tuple(t for t in ALL_TABLES if t not in no_updated_at)
